### ISSUE TITLE
Wrong data in volumechange view/export

### ISSUE THREAD

**Issue by eliasho** [GLAMOS/database#10]
Last parameter in volumechange.csv datafile: geodetic massbalance (Bgeod) is wrong. Calculation/formula need to be adapted.

**Comment by yweidmann** [comment]
The calculation is done in the [view volume_change.length_change.csv_length_change_data](https://github.com/GLAMOS/database/blob/master/src/CREATE/volume_change/CREATE_csv_volume_change_data.sql).

**Comment by eliasho** [comment]
general formula:
((volumechange*1000) / ((avg(area_from,area_to)* (date_to-date_from)))*0.85
hast been adapted. The output has been checked.
