### ISSUE TITLE
Only public volume_change data have to be exported.

### ISSUE THREAD

**Issue by yweidmann** [GLAMOS/database#11]
The colume fk_data_embargo_type has to be added to the table volume_change.volume_change.

**Comment by yweidmann** [comment]
Colume is added with the [ALTER script](https://github.com/GLAMOS/database/blob/master/src/ALTER/volume_change/ALTER_volume_change-fk_data_embargo_type.sql).

All records are set to _Public_ (value = 0). For data which have not to be exported, set the value to _Protected_ (value = 11).

**Comment by eliasho** [comment]
its done by the volumchange reader during the import of the volume change data
