### ISSUE TITLE
The date quality flags for the from and to date of volume changes has to be added

### ISSUE THREAD

**Issue by yweidmann** [GLAMOS/database#12]
The two dates (from and to) of the table _volume_change.volume_change_ have to be tagged with the date-quality-flag.

**Comment by yweidmann** [comment]
Both flags have been added using the [ALTER script](https://github.com/GLAMOS/database/blob/master/src/ALTER/volume_change/ALTER_volume_change-fk_date_quality_type.sql).

All records are set to _Estimated value, only year is known_ (value = 11). If dates are known precisely, the values have to be set to _Precise value known_ (value = 1).

**Comment by eliasho** [comment]
the data quality flag of from_ and to_date is during the import of data using the method within volume change reader.
