### ISSUE TITLE
Improving of Python code for CSV exports

### ISSUE THREAD

**Issue by yweidmann** [GLAMOS/database#13]
Several improvements have to be done:

- Better structuring of the files (e.g. only one folder with Python code)
- Config file for DB access
- Config file entries for the individual citation text.
- Logging

Example of config file:
---
[db_access]
host = xxxxxx
dbName = xxxxxx
dbUser = xxxxxx
dbPassword = xxxxxx
timeout = xxxxxx

[length_change]
citation = xxxxxx

[volume_change]
citation = xxxxxx

[mass_balance]
citation = xxxxxx

[inventory]
citation = xxxxxx
---

**Comment by eliasho** [comment]
updated for all current exports including glacier_list.csv
